models:
  image: tp33/django
  external_links:
    - mysql:db
  ports:
    - "8001:8000"
  volumes:
    - ./models/:/app
  command: bash /app/scripts/startup.sh

exp:
  image: tp33/django
  links:
    - models:models-api
  volumes:
    - ./exp/:/app
  ports:
    - "8002:8000"
  command: bash /app/scripts/startup.sh

web:
  image: tp33/django
  links:
    - exp:exp-api
  volumes:
    - ./web/:/app
  command: bash /app/scripts/startup.sh

